version: 2

models:
  - name: whs_ga__base_events
    description: GAのイベントを `event_date` でパーティショニングしたテーブル
  - name: whs_ga__base_events_intraday
    description: GAのストリーミングされたイベントのテーブル
  - name: whs_ga__events
    description: 分析用に `base_events` と `base_events_intraday` を結合したテーブル

# 基本イベント
  - name: whs_ga__page_views
    description: ページを開いたときに記録されるイベント
    columns:
      - name: page_url
        tests:
          - not_null
  - name: whs_ga__clicks
    description: リンクをクリックしたときに記録されるイベント
    columns:
      - name: link_url
        tests:
          - not_null
  - name: whs_ga__read_to_ends
    description: 記事を読了したときに記録されるイベント
    columns:
      - name: article_id
        tests:
          - not_null

# 集計済みテーブル
  - name: whs_ga__sessions
    description: セッションの情報を格納
    columns:
      - name: session_key
        tests:
          - not_null
          - unique
  - name: whs_ga__users
    description: ユーザーの情報を格納
