version: 2

sources:
  - name: ga
    database: your_gcp_project
    schema: your_dataset # analytics_*******
    tables:
      - name: events
        identifier: events_*
        description: GA4のエクスポートされたイベント。日付でシャーディングされている。エクスポートタイミングは遅れることがある。
      - name: events_intraday
        identifier: events_intraday_*
        description: GA4のストリーミングエクスポートされたイベント。eventsにまだエクスポートされていないデータが入っている。
      - name: events_intraday_today
        identifier: events_intraday_{{ run_started_at.astimezone(modules.pytz.timezone("Asia/Tokyo")).strftime("%Y%m%d") }}
        description: GA4のストリーミングエクスポートされた当日のイベント。eventsにまだエクスポートされていないデータが入っている。
